### ISSUE TITLE
Doesn't work on some website, e.g. GitHub

### ISSUE THREAD

**Issue by kchanqvq** [canatella/xwwp#10]
I was testing on this page https://github.com/emacs-tw/awesome-emacs.
The `xwwp-follow-link` takes no effect.

There are plenty of links on this page.
In fact, I suspect that the problem is somewhere in those `inject-html` or
`inject-js` code, since I'm using the xwwp framework to implement some keyboard navigation command and they took no effect on GitHub either --
but works fine on other webpages.

**Comment by kchanqvq** [comment]
I verified that in GitHub, `window.__xwidget_plus_xxx` is undefined (while
on other website where this work, it's the defined function)

**Comment by kchanqvq** [comment]
I think it might be the case that in the GitHub page, the script added to the `header` DOM node isn't executed. 

A workaround is to directly use `xwidget-webkit-execute-script`, which seems to work, for function definitions.

**Comment by kchanqvq** [comment]
This change fixed it for my usage of `xwwp-js-def`
```
(defun xwwp-html-inject-script (xwidget id script)
  "Inject javascript SCRIPT in XWIDGET session using a script element with ID."
  (xwidget-webkit-execute-script xwidget script))
```
But somehow breaks `xwwp-follow-link`

**Comment by kchanqvq** [comment]
emm after some mysterious tweaking (during implementing other stuff)
it works on my machine now.
Closing this for now and I’ll submit everything I have in a later PR.

p.s. This comment is send using `xwwp` complete free of mouse!

**Comment by canatella** [comment]
> p.s. This comment is send using `xwwp` complete free of mouse!

Nice :) But pay attention that the xwidget webkit is not a real browser. I have no idea about the security implication of doing full fledged browsing with it regarding cookie stealing, sand boxing of the browser itself etc. I would certainly not use it for my banking needs ;)

May I also suggest that when you discover an issue, you start emacs with `-q` to avoid interference with other package, require xwwp manually in the scratch buffer then try to reproduce the issue. Due to the dynamic behaviour of Emacs, with this way you can be sure to test the right code.
