### ISSUE TITLE
dependency ivy is not listed in Package-Requires of xwwp-follow-link-ivy.el

### ISSUE THREAD

**Issue by jian-lin** [canatella/xwwp#18]
ref: https://github.com/NixOS/nixpkgs/issues/335442

**Comment by canatella** [comment]
They are not because I don't want ivy user to have to install helm, etc. If I declare those explicitly in the package, then everybody needs ivy, helm and consult. Ivy, Helm and Consult user are already installing those manually. I also don't want to create a package per completion system and ending up managing 3 micro packages.

**Comment by jian-lin** [comment]
> I also don't want to create a package per completion system and ending up managing 3 micro packages.

I am afraid you already created packages per completion system and ended up with 3 packages.  See https://github.com/melpa/melpa/pull/6755/files.  That is a good practice.  One minor issues here is that `ivy` is not declared as a dependency of [xwwp-follow-link-ivy].

similar for https://github.com/canatella/xwwp/issues/19

[xwwp-follow-link-ivy]: https://melpa.org/#/xwwp-follow-link-ivy
