### ISSUE TITLE
dependency helm is not listed in Package-Requires of xwwp-follow-link-helm.el

### ISSUE THREAD

**Issue by jian-lin** [canatella/xwwp#19]
ref: https://github.com/NixOS/nixpkgs/issues/335442

**Comment by jian-lin** [comment]
Actually, depending on helm-core instead of helm is enough.

**Comment by canatella** [comment]
They are not because I don't want ivy user to have to install helm, etc. If I declare those explicitly in the package, then everybody needs ivy, helm and consult. Ivy, Helm and Consult user are already installing those manually. I also don't want to create a package per completion system and ending up managing 3 micro packages.
